
<div class="content">
<?php View::content(); ?>

 
<?php echo Form::open(); // por defecto llama a la misma url ?>
  
    <table>
    <tr>
        <td><strong>Nombre *:</strong> <br><br></td>
        <td> <?php echo Form::text('usuario.nombre', "placeholder='Ingrese su nombre'") ?> <br><br></td>
       
    </tr>
   
    <tr>
        <td><strong>Apellido *:</strong><br><br></td>
        <td><?php echo Form::text('usuario.apellido', "placeholder='Ingrese su apellido'") ?><br><br></td>
          
    </tr> 
  
     
    <tr>
        <td><strong>Correo *:</strong><br><br></td>
        <td><?php echo Form::text('usuario.correo', "placeholder='Ingrese su correo'") ?><br><br></td>
    </tr>
   
     <tr>
        <td><strong>Contraseña *:</strong><br><br></td>
        <td><?php echo Form::pass('usuario.contrasena', "placeholder='Ingrese su contraseña'") ?><br><br></td>
       
        
   
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td> <?php echo Form::submit('Registrar') ?> <?php echo Form::reset("Limpiar Campos"); ?></td>
        <td> <input type="reset" value="Cancelar" onclick="location='../'" /></td>
       
    </tr>
   <tr>
        <td>&nbsp;</td>
       
       
    </tr>
</table>
      
<?php echo Form::close() ?>
    
    
</div>
