<div class="content">
<?php View::content(); ?>

<?php echo Form::open(); // por defecto llama a la misma url ?>
        
<table>
   
    <tr>
        <td>Nombre proyecto *: <br><br></td>
        <td><?php echo Form::text('proyecto.nombre', "placeholder='Ingrese nombre del proyecto'") ?><br><br></td>
    </tr>
    <tr>
        <td>Descripción : <br><br></td>
        <td> <?php echo Form::textarea('proyecto.descripcion', "placeholder='Ingrese una descripción sobre el proyecto'") ?><br><br></td>
    </tr>  
    <tr>
        <td>Fecha de inicio *: <br><br></td>
        <td><?php echo Form::date('proyecto.fechaInicio') ?><br><br></td>
    </tr> 
    <tr>
        <td>Fecha de finalización *: <br><br></td>
        <td> <?php echo Form::date('proyecto.fechaFin') ?><br><br></td>
    </tr>  
    
        
        <td>&nbsp;</td>
        <td> <?php echo Form::submit('Crear proyecto') ?></td>
    </tr>
</table>
         
<?php echo Form::close() ?>
</div>


