<div class="content">
<?php View::content(); ?>

 
<?php echo Form::open(); // por defecto llama a la misma url ?>
        
<table>
    <tr>
        <td>Nombre proyecto *: </td>
        <td><?php echo Form::text('proyecto.nombre') ?></td>
    </tr>
    <tr>
        <td>Descripción :</td>
        <td> <?php echo Form::text('proyecto.descripcion') ?></td>
    </tr>  
    <tr>
        <td>Fecha de inicio *:</td>
        <td><?php echo Form::date('proyecto.fechaInicio') ?></td>
    </tr> 
    <tr>
        <td>Fecha de finalización *:</td>
        <td> <?php echo Form::date('proyecto.fechaFin') ?></td>
    </tr>
   
<!--    <tr>
        <td>Estado *:</td>
        <td> <input type="text" name="proyecto[estado]"  value=Abierto> </td>
    </tr>-->
   
    
        
        <td>&nbsp;</td>
        <td> <?php echo Form::submit('Registrar proyecto') ?></td>
    </tr>
</table>
         
<?php echo Form::close() ?>
</div>


