<div class="content">
    <?php echo View::content(); ?>
    <h3>Proyectos</h3>
    
    <table border="1" WIDTH=50%>
    <tr>
        <td><strong>Rol</strong></td>
        <td><strong>Nombre proyecto</strong> </td>
        <td><strong>Opciones</strong> </td>
       
    </tr>
    <?php foreach ($listProyectos->items as $item) : ?>
    <tr>
         <td></td>
         <td><?php echo Html::linkAction("#" ,$item->nombre );?></td>
         <td><?php echo Html::linkAction("edit/$item->id/", Html::img('editar.png')) ?>   <?php echo Html::linkAction("edit/$item->id/",  Html::img('cancelar.png')) ?></td>
        
    </tr>
     <?php endforeach; ?>
    
     </table>
</div>