  <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            <?php echo $titulo ?> <small><?php echo $subtitulo ?></small>
                        </h1>
                        <ol class="breadcrumb">
                            <li class="active">
                                <i class="fa fa-dashboard"></i> Dashboard
                            </li>
                        </ol>
                    </div>
                </div>

