<!DOCTYPE html>
<html>
<head>
	<title>soy la prueba</title>
</head>
<body>
    <h2>SCRUMSY</h2>
    
    <p>Aplicacion enfocada al manejo de proyectos, desarrollada bajo la metodología agíl "SCRUM";
        se realiza usando el framework de desarrollo llamado "KUMBIAPHP"
        el cual utiliza el lenguaje PHP y cuya documentacion viene en español y
        es un producto colombiano.</p>
    
    <h2>OBJETIVO </h2>
    
    <p> El objetivo de Scrumsy es ser una aplicación web de ayuda en la construción de proyectos.
        Incluye varias características para la facilidad de uso y la colaboración; 
        Scrumsy busca ser una plataforma de gran utilidad en la realización de proyectos de cualquier tamaño; 
        cuenta con  una interfaz amigable y de facil uso para el usuario.

 
        
    </p>
    <h2>EQUIPO DE DESARROLLO</h2>
    <ul>
        
        <li>CLAUDIA YISEL CALDON </li>
        <p>ccaldono@unicauca.edu.co</p>
        <P>Desarrolladora</P>
        <li>KEYLA DEL MAR PAZ VALENCIA</li>
        <p>keilapaz@unicauca.edu.co</p>
        <P>Desarrolladora</P>
        <li>OMAR RICARDO BONILLA</li>
        <p>ricardobo@unicauca.edu.co</p>
        <P>Desarrollador</P>
        <li>JUAN MANUEL MUÑOZ SOLARTE</li>
        <p>jmamunoz@unicauca.edu.co</p>
        <P>Desarrollador</P>
        <li>ARLEY PERAFAN BUITRON</li>
        <p>aperafan@unicauca.edu.co</p>
        <P>Desarrollador</P>
        <li>WILLIAM FERNANDO ROMERO OTAYA</li>
        <p>wfromero@unicauca.edu.co</p>
        <P>Desarrollador</P>
        <li>WILSON LIBARDO PANTOJA YEPEZ</li>
        <p>wpantoja@unicauca.edu.co</p>
        <P>Product owner</P>
        

        
    </ul>
    <?php echo Html::img("test6.png")?>
</body>
</html>

