<!DOCTYPE html>
<html>
<head>
	<title>soy la prueba</title>
</head>
<body>
    <p>Aplicacion enfocada al manejo de proyectos, aplicando la metodología agil 
        SCRUM; se realiza usando el framework de desarrollo llamado KUMBIA
        el cual utiliza el lenguaje PHP y cuya documentacion viene en Español,
        es un producto colombiano.</p>
    <h3>EQUIPO DE DESARROLLO</h3>
    <ul>
        <li>WILLIAM ROMERO</li>
        <li>JUAN MUÑOZ</li>
        <li>CLAUDIA CALDON</li>
        <li>KEYLA PAZ</li>
        <li>RICARDO BONILLA</li>
        <li>ARLEY PERAFAN</li>
    </ul>
</body>
</html>
