<div>
    <?php View::content(); ?>
    <?php echo Form::open();?>
  <div ><h3>Inicio de Sesion</h3>      
  </div>
    <div><em>Los campos con * son obligatorios</em></div>
    
  <div>
    <div><br/><br/><label for="correo">Correo*: </label><br/><br/></div>
    <div><?php echo Form::text("correo", "placeholder='Ingrese su correo'"); ?><br/><br/><br/></div>
  </div>
  <div>
    <div><label for="contrasena">Contraseña*: </label><br/><br/></div>
    <div ><?php echo Form::pass("contrasena", "placeholder='Ingrese su contraseña'"); ?><br/><br/></div>
  </div>
  <div>
       <ul> <?php echo Form::submit("Ingresar","class: boton"); ?><br/><br/></ul>
  </div>
  <div>
      <a href="#" >¿Olvidó su contraseña?</a>
  </div>
             
        <div>
            <ul class="actions">
                <input type="reset" value="¡Registrarme!" onclick="location='usuarios/registrarUsuario'" />
            </ul>
        </div>
  
  <?php echo Form::close(); ?></p>
                       
</div>