<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by TEMPLATED
http://templated.co
Released for free under the Creative Commons Attribution License

Name       : TwoFold 
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20130526

-->
<html xmlns="http://www.w3.org/1999/xhtml">

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,600,700" rel="stylesheet" />
    <!--<link href="default.css" rel="stylesheet" type="text/css" media="all" />-->
    <?php echo Tag::css('acceso/default') ?>

    <?php echo Html::includeCss() ?>

    <!--[if IE 6]>
    <link href="default_ie6.css" rel="stylesheet" type="text/css" />
    <![endif]-->

    <body>
        <div id="header" class="container">
            <div id="logo">
                <h1><a>SCRUMSY</a></h1>
            </div>

        </div>
        <div id="wrapper">
            <div id="welcome" class="wrapper-style1">
                <div class="title">
                    <h2>Registro de Usuario</h2>
                    <span class="byline"></span> </div>
                <div id="box2">
                    <font color="#FFFFFF">
                        Este texto está en azul usando color=""
                    </font>
                </div>


                <div id="box2">

                   
                    <form method="post" action="#">

                        <div class="row uniform 50%">
                            <?php View::content() ?>                          
                        </div>
                    </form>


                    <!--<ul class="actions">
                            <li><a href="#" class="button special big">Restaurar</a></li>
                    </ul> -->
                </div>

            </div>
        </div>

        <div id="footer" class="container">
            <div>
                <div>
                    <h3><font color="#FFFFFF"><em>Redes sociales</em></font></h3>
                </div>
                <ul class="contact">
                    <li><a href="https://twitter.com" class="icon icon-twitter"><span>Twitter</span></a></li>
                    <li><a href="https://facebook.com" class="icon icon-facebook"><span>Facebook</span></a></li>




                </ul>
            </div>
            <p>&copy; Untitled. | Photos by <a href="http://fotogrph.com/">Fotogrph</a> | Design by <a href="http://templated.co" rel="nofollow">TEMPLATED</a>.</p>
        </div>
    </body>
</html>
