<!DOCTYPE html>
<html>
<head>
	<title>soy el inicio</title>
</head>
<body>
    <h1>¡BIENVENIDO!</h1>
    <p>Esta aplicación te permite multiples funciones; aqui puedes crear un nuevo proyecto
    y en él, integrar grupos de trabajo, crear sprints con las tareas de cada uno, ademas de 
    asignarlas a cada miembro del equipo.
    Puedes tambien, ver los proyectos a los que perteneces con un rol diferente al de administrador,
    puedes ver tus tareas así como tambien graficas de horas restantes por sprint.</p>
</body>
</html>
