<!DOCTYPE html>
<html>
<head>
	<title>¡BIENVENIDO!</title>
</head>
<body text-center>
    <h1>SCRUMSY</h1>
    
    
    <p>
        
        
        
    </p>
    <p>Esta aplicación ofrece múltiples funcionalidades, dirigidas hacia el desarrollo de proyectos, 
        utilizando "Scrum" como metodología para la comunicación e interacción del equipo. 
        Dentro de la aplicación se podrá navegar de forma amigable, ya que provee interfaces
        intuitivas y de alto nivel, también provee creación de artefactos propios de la metodología "Scrum"
        tales como el Backlog de producto,
        el Backlog de Sprint y Scrum Taskboar y el incremento de funcionalidad.</p>
    
    <!----- cambiar la imagen con algo referente a Scrumsy ------->
    <?php echo Html::img("test6.png")?>
    
</body>
</html>
