<!DOCTYPE html>
<html>
<head>
	<title>soy el inicio</title>
</head>
<body>
    <h1>¡BIENVENIDO!</h1>
    <p>Esta aplicación ofrece múltiples funcionalidades, dirigidas hacia el desarrollo de proyectos, 
        utilizando "Scrum" como metodología para la comunicación e interacción del equipo. 
        Dentro de la aplicación se podrá navegar de forma amigable, ya que provee interfaces
        intuitivas y de alto nivel, también provee creación de artefactos propios de la metodología "Scrum"
        tales como el Backlog de producto,
        el Backlog de Sprint y Scrum Taskboar y el incremento de funcionalidad.</p>
</body>
</html>
